### ISSUE TITLE
vmware driver error

### ISSUE THREAD

**Issue by frank3427** [chrisipa/packer-esxi#2]
I am using you templates. 

how do i get past this error?

Build 'my-vm' errored: Failed creating VMware driver: Unable to initialize any driver for this platform. The errors
from each driver are shown below. Please fix at least one driver
to continue:
* ssh: handshake failed: ssh: unable to authenticate, attempted methods [none keyboard-interactive], no supported methods remain

==> Some builds didn't complete successfully and had errors:
--> my-vm: Failed creating VMware driver: Unable to initialize any driver for this platform. The errors
from each driver are shown below. Please fix at least one driver
to continue:
* ssh: handshake failed: ssh: unable to authenticate, attempted methods [none keyboard-interactive], no supported methods remain

==> Builds finished but no artifacts were created.

**Comment by chrisipa** [comment]
Hi,

are you using the free ESXi variant from VMWare or the commercial vSphere?

I'm asking because this project is targeted towards the free version.
As far as I know VM templates are not supported here.

You should also have a look at this GitHub project:

https://github.com/chrisipa/cloud-portal

Here you can also use can VM templates for vSphere provisionings.

**Comment by frank3427** [comment]
I am using the free esxi version,

**Comment by chrisipa** [comment]
Did you activate the SSH service as documented in the README.md file?

**Comment by frank3427** [comment]
Yes, I am now able to build OVF

**Comment by chrisipa** [comment]
Great that it also worked for you ...
